services:
  frontend:
    image: example-frontend
    ports:
      - 5000:5000
    container_name: example-frontend

  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis-db
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PASSWORD=example
    depends_on:
      - postgresDB
      - redisDB
    container_name: example-backend

  redisDB:
    image: redis
    restart: unless-stopped
    container_name: redis-db

  postgresDB:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    container_name: postgres-db
    volumes:
      - ./database:/var/lib/postgresql/data

  nginxProxy:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx-proxy
