name: Simple Express App

on:
  push:
    branches:
      - main

jobs:
  publish-docer-hub:
    name: Publishes image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      #Checkout to the repository
      - name: Checkout
        uses: actions/checkout@v4

      #Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
