services:
  frontend:
    image: example-frontend
    ports:
      - 5000:5000
    container_name: example-frontend

  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis-db
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PASSWORD=example
    container_name: example-backend

  db:
    image: redis
    restart: unless-stopped
    container_name: redis-db

  messageDB:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    container_name: postgres-db
    volumes:
      - ./database:/var/lib/postgresql/data
