services:
  frontend:
    image: example-frontend
    ports:
      - 5000:5000
    container_name: example-frontend

  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=example-db
    container_name: example-backend

  db:
    image: redis
    restart: unless-stopped
    container_name: example-db
